services:
  static:
    container_name: blog.surister.dev
    image: node
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - 80
    command: node /dist/index.mjs
    environment:
      - VIRTUAL_HOST=blog.surister.dev
      - NGINX_HOST=blog.surister.dev
      - NITRO_PORT=80
    volumes:
      - .dist/:/dist

networks:
  proxy:
    name: proxy
    external: true
